### PR TITLE
Job #1 Install dependencies and run tests. 

### PR DESCRIPTION
**Pull request by optimusinhisprime**
Added a job to install the dependencies and run the app tests.

### CODE REVIEW

**Review by ChinyangaTL — COMMENTED** [review]
This is brilliant work sir, I imagine that circle ci runs green?

**Comment by optimusinhisprime** [comment]
Yea everything is all green rn.

**Review by Montso-Matlaletsa — APPROVED** [review]
This is nice. Good work men!

**Comment by rmoswela** [comment]
Awesome work dude.

**Comment by optimusinhisprime** [comment]
Thank You @rmoswela

**Pull request merged**
